//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 8/30/2009 8:33:07 AM
namespace MultiLearn.Data.Log
{
    
    /// <summary>
    /// There are no comments for SqliteLog in the schema.
    /// </summary>
    public partial class SqliteLog : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new SqliteLog object using the connection string found in the 'SqliteLog' section of the application configuration file.
        /// </summary>
        public SqliteLog() : 
                base("name=SqliteLog", "SqliteLog")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new SqliteLog object.
        /// </summary>
        public SqliteLog(string connectionString) : 
                base(connectionString, "SqliteLog")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new SqliteLog object.
        /// </summary>
        public SqliteLog(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "SqliteLog")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for UserClassSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<UserClass> UserClassSet
        {
            get
            {
                if ((this._UserClassSet == null))
                {
                    this._UserClassSet = base.CreateQuery<UserClass>("[UserClassSet]");
                }
                return this._UserClassSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<UserClass> _UserClassSet;
        /// <summary>
        /// There are no comments for MultiChoiceQuestionSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<MultiChoiceQuestion> MultiChoiceQuestionSet
        {
            get
            {
                if ((this._MultiChoiceQuestionSet == null))
                {
                    this._MultiChoiceQuestionSet = base.CreateQuery<MultiChoiceQuestion>("[MultiChoiceQuestionSet]");
                }
                return this._MultiChoiceQuestionSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<MultiChoiceQuestion> _MultiChoiceQuestionSet;
        /// <summary>
        /// There are no comments for MultiMathQuestionSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<MultiMathQuestion> MultiMathQuestionSet
        {
            get
            {
                if ((this._MultiMathQuestionSet == null))
                {
                    this._MultiMathQuestionSet = base.CreateQuery<MultiMathQuestion>("[MultiMathQuestionSet]");
                }
                return this._MultiMathQuestionSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<MultiMathQuestion> _MultiMathQuestionSet;
        /// <summary>
        /// There are no comments for MultiSpellMistakeSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<MultiSpellMistake> MultiSpellMistakeSet
        {
            get
            {
                if ((this._MultiSpellMistakeSet == null))
                {
                    this._MultiSpellMistakeSet = base.CreateQuery<MultiSpellMistake>("[MultiSpellMistakeSet]");
                }
                return this._MultiSpellMistakeSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<MultiSpellMistake> _MultiSpellMistakeSet;
        /// <summary>
        /// There are no comments for MultiSpellQuestionSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<MultiSpellQuestion> MultiSpellQuestionSet
        {
            get
            {
                if ((this._MultiSpellQuestionSet == null))
                {
                    this._MultiSpellQuestionSet = base.CreateQuery<MultiSpellQuestion>("[MultiSpellQuestionSet]");
                }
                return this._MultiSpellQuestionSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<MultiSpellQuestion> _MultiSpellQuestionSet;
        /// <summary>
        /// There are no comments for SessionSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Session> SessionSet
        {
            get
            {
                if ((this._SessionSet == null))
                {
                    this._SessionSet = base.CreateQuery<Session>("[SessionSet]");
                }
                return this._SessionSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Session> _SessionSet;
        /// <summary>
        /// There are no comments for LogUserSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<LogUser> LogUserSet
        {
            get
            {
                if ((this._LogUserSet == null))
                {
                    this._LogUserSet = base.CreateQuery<LogUser>("[LogUserSet]");
                }
                return this._LogUserSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<LogUser> _LogUserSet;
        /// <summary>
        /// There are no comments for UserSessionSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<UserSession> UserSessionSet
        {
            get
            {
                if ((this._UserSessionSet == null))
                {
                    this._UserSessionSet = base.CreateQuery<UserSession>("[UserSessionSet]");
                }
                return this._UserSessionSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<UserSession> _UserSessionSet;
        /// <summary>
        /// There are no comments for KeystrokesSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Keystrokes> KeystrokesSet
        {
            get
            {
                if ((this._KeystrokesSet == null))
                {
                    this._KeystrokesSet = base.CreateQuery<Keystrokes>("[KeystrokesSet]");
                }
                return this._KeystrokesSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Keystrokes> _KeystrokesSet;
        /// <summary>
        /// There are no comments for UserClassSet in the schema.
        /// </summary>
        public void AddToUserClassSet(UserClass userClass)
        {
            base.AddObject("UserClassSet", userClass);
        }
        /// <summary>
        /// There are no comments for MultiChoiceQuestionSet in the schema.
        /// </summary>
        public void AddToMultiChoiceQuestionSet(MultiChoiceQuestion multiChoiceQuestion)
        {
            base.AddObject("MultiChoiceQuestionSet", multiChoiceQuestion);
        }
        /// <summary>
        /// There are no comments for MultiMathQuestionSet in the schema.
        /// </summary>
        public void AddToMultiMathQuestionSet(MultiMathQuestion multiMathQuestion)
        {
            base.AddObject("MultiMathQuestionSet", multiMathQuestion);
        }
        /// <summary>
        /// There are no comments for MultiSpellMistakeSet in the schema.
        /// </summary>
        public void AddToMultiSpellMistakeSet(MultiSpellMistake multiSpellMistake)
        {
            base.AddObject("MultiSpellMistakeSet", multiSpellMistake);
        }
        /// <summary>
        /// There are no comments for MultiSpellQuestionSet in the schema.
        /// </summary>
        public void AddToMultiSpellQuestionSet(MultiSpellQuestion multiSpellQuestion)
        {
            base.AddObject("MultiSpellQuestionSet", multiSpellQuestion);
        }
        /// <summary>
        /// There are no comments for SessionSet in the schema.
        /// </summary>
        public void AddToSessionSet(Session session)
        {
            base.AddObject("SessionSet", session);
        }
        /// <summary>
        /// There are no comments for LogUserSet in the schema.
        /// </summary>
        public void AddToLogUserSet(LogUser logUser)
        {
            base.AddObject("LogUserSet", logUser);
        }
        /// <summary>
        /// There are no comments for UserSessionSet in the schema.
        /// </summary>
        public void AddToUserSessionSet(UserSession userSession)
        {
            base.AddObject("UserSessionSet", userSession);
        }
        /// <summary>
        /// There are no comments for KeystrokesSet in the schema.
        /// </summary>
        public void AddToKeystrokesSet(Keystrokes keystrokes)
        {
            base.AddObject("KeystrokesSet", keystrokes);
        }
    }
    /// <summary>
    /// There are no comments for MultiLearn.Data.Log.UserClass in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MultiLearn.Data.Log", Name="UserClass")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class UserClass : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new UserClass object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        public static UserClass CreateUserClass(long id)
        {
            UserClass userClass = new UserClass();
            userClass.id = id;
            return userClass;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private long _id;
        partial void OnidChanging(long value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
    }
    /// <summary>
    /// There are no comments for MultiLearn.Data.Log.MultiChoiceQuestion in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MultiLearn.Data.Log", Name="MultiChoiceQuestion")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class MultiChoiceQuestion : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new MultiChoiceQuestion object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        /// <param name="user_id">Initial value of user_id.</param>
        /// <param name="session_id">Initial value of session_id.</param>
        /// <param name="difficulty">Initial value of difficulty.</param>
        /// <param name="questionset_name">Initial value of questionset_name.</param>
        /// <param name="question_id">Initial value of question_id.</param>
        /// <param name="number">Initial value of number.</param>
        /// <param name="start">Initial value of start.</param>
        public static MultiChoiceQuestion CreateMultiChoiceQuestion(long id, long user_id, long session_id, double difficulty, string questionset_name, long question_id, long number, global::System.DateTime start)
        {
            MultiChoiceQuestion multiChoiceQuestion = new MultiChoiceQuestion();
            multiChoiceQuestion.id = id;
            multiChoiceQuestion.user_id = user_id;
            multiChoiceQuestion.session_id = session_id;
            multiChoiceQuestion.difficulty = difficulty;
            multiChoiceQuestion.questionset_name = questionset_name;
            multiChoiceQuestion.question_id = question_id;
            multiChoiceQuestion.number = number;
            multiChoiceQuestion.start = start;
            return multiChoiceQuestion;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private long _id;
        partial void OnidChanging(long value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property user_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long user_id
        {
            get
            {
                return this._user_id;
            }
            set
            {
                this.Onuser_idChanging(value);
                this.ReportPropertyChanging("user_id");
                this._user_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("user_id");
                this.Onuser_idChanged();
            }
        }
        private long _user_id;
        partial void Onuser_idChanging(long value);
        partial void Onuser_idChanged();
        /// <summary>
        /// There are no comments for Property session_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long session_id
        {
            get
            {
                return this._session_id;
            }
            set
            {
                this.Onsession_idChanging(value);
                this.ReportPropertyChanging("session_id");
                this._session_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("session_id");
                this.Onsession_idChanged();
            }
        }
        private long _session_id;
        partial void Onsession_idChanging(long value);
        partial void Onsession_idChanged();
        /// <summary>
        /// There are no comments for Property difficulty in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double difficulty
        {
            get
            {
                return this._difficulty;
            }
            set
            {
                this.OndifficultyChanging(value);
                this.ReportPropertyChanging("difficulty");
                this._difficulty = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("difficulty");
                this.OndifficultyChanged();
            }
        }
        private double _difficulty;
        partial void OndifficultyChanging(double value);
        partial void OndifficultyChanged();
        /// <summary>
        /// There are no comments for Property questionset_name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string questionset_name
        {
            get
            {
                return this._questionset_name;
            }
            set
            {
                this.Onquestionset_nameChanging(value);
                this.ReportPropertyChanging("questionset_name");
                this._questionset_name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("questionset_name");
                this.Onquestionset_nameChanged();
            }
        }
        private string _questionset_name;
        partial void Onquestionset_nameChanging(string value);
        partial void Onquestionset_nameChanged();
        /// <summary>
        /// There are no comments for Property question_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long question_id
        {
            get
            {
                return this._question_id;
            }
            set
            {
                this.Onquestion_idChanging(value);
                this.ReportPropertyChanging("question_id");
                this._question_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("question_id");
                this.Onquestion_idChanged();
            }
        }
        private long _question_id;
        partial void Onquestion_idChanging(long value);
        partial void Onquestion_idChanged();
        /// <summary>
        /// There are no comments for Property number in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long number
        {
            get
            {
                return this._number;
            }
            set
            {
                this.OnnumberChanging(value);
                this.ReportPropertyChanging("number");
                this._number = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("number");
                this.OnnumberChanged();
            }
        }
        private long _number;
        partial void OnnumberChanging(long value);
        partial void OnnumberChanged();
        /// <summary>
        /// There are no comments for Property answer in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> answer
        {
            get
            {
                return this._answer;
            }
            set
            {
                this.OnanswerChanging(value);
                this.ReportPropertyChanging("answer");
                this._answer = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("answer");
                this.OnanswerChanged();
            }
        }
        private global::System.Nullable<long> _answer;
        partial void OnanswerChanging(global::System.Nullable<long> value);
        partial void OnanswerChanged();
        /// <summary>
        /// There are no comments for Property correct in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> correct
        {
            get
            {
                return this._correct;
            }
            set
            {
                this.OncorrectChanging(value);
                this.ReportPropertyChanging("correct");
                this._correct = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("correct");
                this.OncorrectChanged();
            }
        }
        private global::System.Nullable<bool> _correct;
        partial void OncorrectChanging(global::System.Nullable<bool> value);
        partial void OncorrectChanged();
        /// <summary>
        /// There are no comments for Property start in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime start
        {
            get
            {
                return this._start;
            }
            set
            {
                this.OnstartChanging(value);
                this.ReportPropertyChanging("start");
                this._start = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("start");
                this.OnstartChanged();
            }
        }
        private global::System.DateTime _start;
        partial void OnstartChanging(global::System.DateTime value);
        partial void OnstartChanged();
        /// <summary>
        /// There are no comments for Property end in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> end
        {
            get
            {
                return this._end;
            }
            set
            {
                this.OnendChanging(value);
                this.ReportPropertyChanging("end");
                this._end = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("end");
                this.OnendChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _end;
        partial void OnendChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnendChanged();
    }
    /// <summary>
    /// There are no comments for MultiLearn.Data.Log.MultiMathQuestion in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MultiLearn.Data.Log", Name="MultiMathQuestion")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class MultiMathQuestion : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new MultiMathQuestion object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        /// <param name="user_id">Initial value of user_id.</param>
        /// <param name="session_id">Initial value of session_id.</param>
        /// <param name="number">Initial value of number.</param>
        /// <param name="difficulty">Initial value of difficulty.</param>
        /// <param name="x">Initial value of x.</param>
        /// <param name="operand">Initial value of operand.</param>
        /// <param name="y">Initial value of y.</param>
        /// <param name="start">Initial value of start.</param>
        public static MultiMathQuestion CreateMultiMathQuestion(long id, long user_id, long session_id, long number, long difficulty, long x, string operand, long y, global::System.DateTime start)
        {
            MultiMathQuestion multiMathQuestion = new MultiMathQuestion();
            multiMathQuestion.id = id;
            multiMathQuestion.user_id = user_id;
            multiMathQuestion.session_id = session_id;
            multiMathQuestion.number = number;
            multiMathQuestion.difficulty = difficulty;
            multiMathQuestion.x = x;
            multiMathQuestion.operand = operand;
            multiMathQuestion.y = y;
            multiMathQuestion.start = start;
            return multiMathQuestion;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private long _id;
        partial void OnidChanging(long value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property user_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long user_id
        {
            get
            {
                return this._user_id;
            }
            set
            {
                this.Onuser_idChanging(value);
                this.ReportPropertyChanging("user_id");
                this._user_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("user_id");
                this.Onuser_idChanged();
            }
        }
        private long _user_id;
        partial void Onuser_idChanging(long value);
        partial void Onuser_idChanged();
        /// <summary>
        /// There are no comments for Property session_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long session_id
        {
            get
            {
                return this._session_id;
            }
            set
            {
                this.Onsession_idChanging(value);
                this.ReportPropertyChanging("session_id");
                this._session_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("session_id");
                this.Onsession_idChanged();
            }
        }
        private long _session_id;
        partial void Onsession_idChanging(long value);
        partial void Onsession_idChanged();
        /// <summary>
        /// There are no comments for Property number in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long number
        {
            get
            {
                return this._number;
            }
            set
            {
                this.OnnumberChanging(value);
                this.ReportPropertyChanging("number");
                this._number = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("number");
                this.OnnumberChanged();
            }
        }
        private long _number;
        partial void OnnumberChanging(long value);
        partial void OnnumberChanged();
        /// <summary>
        /// There are no comments for Property difficulty in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long difficulty
        {
            get
            {
                return this._difficulty;
            }
            set
            {
                this.OndifficultyChanging(value);
                this.ReportPropertyChanging("difficulty");
                this._difficulty = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("difficulty");
                this.OndifficultyChanged();
            }
        }
        private long _difficulty;
        partial void OndifficultyChanging(long value);
        partial void OndifficultyChanged();
        /// <summary>
        /// There are no comments for Property x in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long x
        {
            get
            {
                return this._x;
            }
            set
            {
                this.OnxChanging(value);
                this.ReportPropertyChanging("x");
                this._x = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("x");
                this.OnxChanged();
            }
        }
        private long _x;
        partial void OnxChanging(long value);
        partial void OnxChanged();
        /// <summary>
        /// There are no comments for Property operand in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string operand
        {
            get
            {
                return this._operand;
            }
            set
            {
                this.OnoperandChanging(value);
                this.ReportPropertyChanging("operand");
                this._operand = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("operand");
                this.OnoperandChanged();
            }
        }
        private string _operand;
        partial void OnoperandChanging(string value);
        partial void OnoperandChanged();
        /// <summary>
        /// There are no comments for Property y in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long y
        {
            get
            {
                return this._y;
            }
            set
            {
                this.OnyChanging(value);
                this.ReportPropertyChanging("y");
                this._y = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("y");
                this.OnyChanged();
            }
        }
        private long _y;
        partial void OnyChanging(long value);
        partial void OnyChanged();
        /// <summary>
        /// There are no comments for Property answer in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> answer
        {
            get
            {
                return this._answer;
            }
            set
            {
                this.OnanswerChanging(value);
                this.ReportPropertyChanging("answer");
                this._answer = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("answer");
                this.OnanswerChanged();
            }
        }
        private global::System.Nullable<long> _answer;
        partial void OnanswerChanging(global::System.Nullable<long> value);
        partial void OnanswerChanged();
        /// <summary>
        /// There are no comments for Property correct in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> correct
        {
            get
            {
                return this._correct;
            }
            set
            {
                this.OncorrectChanging(value);
                this.ReportPropertyChanging("correct");
                this._correct = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("correct");
                this.OncorrectChanged();
            }
        }
        private global::System.Nullable<bool> _correct;
        partial void OncorrectChanging(global::System.Nullable<bool> value);
        partial void OncorrectChanged();
        /// <summary>
        /// There are no comments for Property start in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime start
        {
            get
            {
                return this._start;
            }
            set
            {
                this.OnstartChanging(value);
                this.ReportPropertyChanging("start");
                this._start = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("start");
                this.OnstartChanged();
            }
        }
        private global::System.DateTime _start;
        partial void OnstartChanging(global::System.DateTime value);
        partial void OnstartChanged();
        /// <summary>
        /// There are no comments for Property end in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> end
        {
            get
            {
                return this._end;
            }
            set
            {
                this.OnendChanging(value);
                this.ReportPropertyChanging("end");
                this._end = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("end");
                this.OnendChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _end;
        partial void OnendChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnendChanged();
        /// <summary>
        /// There are no comments for Property user_2_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> user_2_id
        {
            get
            {
                return this._user_2_id;
            }
            set
            {
                this.Onuser_2_idChanging(value);
                this.ReportPropertyChanging("user_2_id");
                this._user_2_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("user_2_id");
                this.Onuser_2_idChanged();
            }
        }
        private global::System.Nullable<long> _user_2_id;
        partial void Onuser_2_idChanging(global::System.Nullable<long> value);
        partial void Onuser_2_idChanged();
    }
    /// <summary>
    /// There are no comments for MultiLearn.Data.Log.MultiSpellMistake in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MultiLearn.Data.Log", Name="MultiSpellMistake")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class MultiSpellMistake : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new MultiSpellMistake object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        /// <param name="question_id">Initial value of question_id.</param>
        /// <param name="word">Initial value of word.</param>
        /// <param name="index">Initial value of index.</param>
        /// <param name="attempt">Initial value of attempt.</param>
        public static MultiSpellMistake CreateMultiSpellMistake(long id, long question_id, string word, long index, string attempt)
        {
            MultiSpellMistake multiSpellMistake = new MultiSpellMistake();
            multiSpellMistake.id = id;
            multiSpellMistake.question_id = question_id;
            multiSpellMistake.word = word;
            multiSpellMistake.index = index;
            multiSpellMistake.attempt = attempt;
            return multiSpellMistake;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private long _id;
        partial void OnidChanging(long value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property question_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long question_id
        {
            get
            {
                return this._question_id;
            }
            set
            {
                this.Onquestion_idChanging(value);
                this.ReportPropertyChanging("question_id");
                this._question_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("question_id");
                this.Onquestion_idChanged();
            }
        }
        private long _question_id;
        partial void Onquestion_idChanging(long value);
        partial void Onquestion_idChanged();
        /// <summary>
        /// There are no comments for Property word in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string word
        {
            get
            {
                return this._word;
            }
            set
            {
                this.OnwordChanging(value);
                this.ReportPropertyChanging("word");
                this._word = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("word");
                this.OnwordChanged();
            }
        }
        private string _word;
        partial void OnwordChanging(string value);
        partial void OnwordChanged();
        /// <summary>
        /// There are no comments for Property index in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long index
        {
            get
            {
                return this._index;
            }
            set
            {
                this.OnindexChanging(value);
                this.ReportPropertyChanging("index");
                this._index = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("index");
                this.OnindexChanged();
            }
        }
        private long _index;
        partial void OnindexChanging(long value);
        partial void OnindexChanged();
        /// <summary>
        /// There are no comments for Property attempt in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string attempt
        {
            get
            {
                return this._attempt;
            }
            set
            {
                this.OnattemptChanging(value);
                this.ReportPropertyChanging("attempt");
                this._attempt = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("attempt");
                this.OnattemptChanged();
            }
        }
        private string _attempt;
        partial void OnattemptChanging(string value);
        partial void OnattemptChanged();
    }
    /// <summary>
    /// There are no comments for MultiLearn.Data.Log.MultiSpellQuestion in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MultiLearn.Data.Log", Name="MultiSpellQuestion")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class MultiSpellQuestion : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new MultiSpellQuestion object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        /// <param name="user_id">Initial value of user_id.</param>
        /// <param name="session_id">Initial value of session_id.</param>
        /// <param name="difficulty">Initial value of difficulty.</param>
        /// <param name="word">Initial value of word.</param>
        /// <param name="number">Initial value of number.</param>
        /// <param name="start">Initial value of start.</param>
        public static MultiSpellQuestion CreateMultiSpellQuestion(long id, long user_id, long session_id, double difficulty, string word, long number, global::System.DateTime start)
        {
            MultiSpellQuestion multiSpellQuestion = new MultiSpellQuestion();
            multiSpellQuestion.id = id;
            multiSpellQuestion.user_id = user_id;
            multiSpellQuestion.session_id = session_id;
            multiSpellQuestion.difficulty = difficulty;
            multiSpellQuestion.word = word;
            multiSpellQuestion.number = number;
            multiSpellQuestion.start = start;
            return multiSpellQuestion;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private long _id;
        partial void OnidChanging(long value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property user_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long user_id
        {
            get
            {
                return this._user_id;
            }
            set
            {
                this.Onuser_idChanging(value);
                this.ReportPropertyChanging("user_id");
                this._user_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("user_id");
                this.Onuser_idChanged();
            }
        }
        private long _user_id;
        partial void Onuser_idChanging(long value);
        partial void Onuser_idChanged();
        /// <summary>
        /// There are no comments for Property session_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long session_id
        {
            get
            {
                return this._session_id;
            }
            set
            {
                this.Onsession_idChanging(value);
                this.ReportPropertyChanging("session_id");
                this._session_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("session_id");
                this.Onsession_idChanged();
            }
        }
        private long _session_id;
        partial void Onsession_idChanging(long value);
        partial void Onsession_idChanged();
        /// <summary>
        /// There are no comments for Property difficulty in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double difficulty
        {
            get
            {
                return this._difficulty;
            }
            set
            {
                this.OndifficultyChanging(value);
                this.ReportPropertyChanging("difficulty");
                this._difficulty = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("difficulty");
                this.OndifficultyChanged();
            }
        }
        private double _difficulty;
        partial void OndifficultyChanging(double value);
        partial void OndifficultyChanged();
        /// <summary>
        /// There are no comments for Property word in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string word
        {
            get
            {
                return this._word;
            }
            set
            {
                this.OnwordChanging(value);
                this.ReportPropertyChanging("word");
                this._word = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("word");
                this.OnwordChanged();
            }
        }
        private string _word;
        partial void OnwordChanging(string value);
        partial void OnwordChanged();
        /// <summary>
        /// There are no comments for Property mistakes in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> mistakes
        {
            get
            {
                return this._mistakes;
            }
            set
            {
                this.OnmistakesChanging(value);
                this.ReportPropertyChanging("mistakes");
                this._mistakes = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("mistakes");
                this.OnmistakesChanged();
            }
        }
        private global::System.Nullable<long> _mistakes;
        partial void OnmistakesChanging(global::System.Nullable<long> value);
        partial void OnmistakesChanged();
        /// <summary>
        /// There are no comments for Property number in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long number
        {
            get
            {
                return this._number;
            }
            set
            {
                this.OnnumberChanging(value);
                this.ReportPropertyChanging("number");
                this._number = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("number");
                this.OnnumberChanged();
            }
        }
        private long _number;
        partial void OnnumberChanging(long value);
        partial void OnnumberChanged();
        /// <summary>
        /// There are no comments for Property correct in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> correct
        {
            get
            {
                return this._correct;
            }
            set
            {
                this.OncorrectChanging(value);
                this.ReportPropertyChanging("correct");
                this._correct = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("correct");
                this.OncorrectChanged();
            }
        }
        private global::System.Nullable<bool> _correct;
        partial void OncorrectChanging(global::System.Nullable<bool> value);
        partial void OncorrectChanged();
        /// <summary>
        /// There are no comments for Property start in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime start
        {
            get
            {
                return this._start;
            }
            set
            {
                this.OnstartChanging(value);
                this.ReportPropertyChanging("start");
                this._start = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("start");
                this.OnstartChanged();
            }
        }
        private global::System.DateTime _start;
        partial void OnstartChanging(global::System.DateTime value);
        partial void OnstartChanged();
        /// <summary>
        /// There are no comments for Property end in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> end
        {
            get
            {
                return this._end;
            }
            set
            {
                this.OnendChanging(value);
                this.ReportPropertyChanging("end");
                this._end = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("end");
                this.OnendChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _end;
        partial void OnendChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnendChanged();
    }
    /// <summary>
    /// There are no comments for MultiLearn.Data.Log.Session in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MultiLearn.Data.Log", Name="Session")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Session : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Session object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        /// <param name="timestamp">Initial value of timestamp.</param>
        public static Session CreateSession(long id, global::System.DateTime timestamp)
        {
            Session session = new Session();
            session.id = id;
            session.timestamp = timestamp;
            return session;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private long _id;
        partial void OnidChanging(long value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property timestamp in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime timestamp
        {
            get
            {
                return this._timestamp;
            }
            set
            {
                this.OntimestampChanging(value);
                this.ReportPropertyChanging("timestamp");
                this._timestamp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("timestamp");
                this.OntimestampChanged();
            }
        }
        private global::System.DateTime _timestamp;
        partial void OntimestampChanging(global::System.DateTime value);
        partial void OntimestampChanged();
        /// <summary>
        /// There are no comments for Property winner_user_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> winner_user_id
        {
            get
            {
                return this._winner_user_id;
            }
            set
            {
                this.Onwinner_user_idChanging(value);
                this.ReportPropertyChanging("winner_user_id");
                this._winner_user_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("winner_user_id");
                this.Onwinner_user_idChanged();
            }
        }
        private global::System.Nullable<long> _winner_user_id;
        partial void Onwinner_user_idChanging(global::System.Nullable<long> value);
        partial void Onwinner_user_idChanged();
    }
    /// <summary>
    /// There are no comments for MultiLearn.Data.Log.LogUser in the schema.
    /// </summary>
    /// <KeyProperties>
    /// uid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MultiLearn.Data.Log", Name="LogUser")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class LogUser : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new LogUser object.
        /// </summary>
        /// <param name="uid">Initial value of uid.</param>
        /// <param name="pin">Initial value of pin.</param>
        public static LogUser CreateLogUser(long uid, long pin)
        {
            LogUser logUser = new LogUser();
            logUser.uid = uid;
            logUser.pin = pin;
            return logUser;
        }
        /// <summary>
        /// There are no comments for Property uid in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long uid
        {
            get
            {
                return this._uid;
            }
            set
            {
                this.OnuidChanging(value);
                this.ReportPropertyChanging("uid");
                this._uid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("uid");
                this.OnuidChanged();
            }
        }
        private long _uid;
        partial void OnuidChanging(long value);
        partial void OnuidChanged();
        /// <summary>
        /// There are no comments for Property pin in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long pin
        {
            get
            {
                return this._pin;
            }
            set
            {
                this.OnpinChanging(value);
                this.ReportPropertyChanging("pin");
                this._pin = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("pin");
                this.OnpinChanged();
            }
        }
        private long _pin;
        partial void OnpinChanging(long value);
        partial void OnpinChanged();
        /// <summary>
        /// There are no comments for Property last_logged_in in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> last_logged_in
        {
            get
            {
                return this._last_logged_in;
            }
            set
            {
                this.Onlast_logged_inChanging(value);
                this.ReportPropertyChanging("last_logged_in");
                this._last_logged_in = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("last_logged_in");
                this.Onlast_logged_inChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _last_logged_in;
        partial void Onlast_logged_inChanging(global::System.Nullable<global::System.DateTime> value);
        partial void Onlast_logged_inChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property class_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> class_id
        {
            get
            {
                return this._class_id;
            }
            set
            {
                this.Onclass_idChanging(value);
                this.ReportPropertyChanging("class_id");
                this._class_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("class_id");
                this.Onclass_idChanged();
            }
        }
        private global::System.Nullable<long> _class_id;
        partial void Onclass_idChanging(global::System.Nullable<long> value);
        partial void Onclass_idChanged();
    }
    /// <summary>
    /// There are no comments for MultiLearn.Data.Log.UserSession in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MultiLearn.Data.Log", Name="UserSession")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class UserSession : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new UserSession object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        /// <param name="user_id">Initial value of user_id.</param>
        /// <param name="session_id">Initial value of session_id.</param>
        /// <param name="correct">Initial value of correct.</param>
        /// <param name="total">Initial value of total.</param>
        /// <param name="start_difficulty">Initial value of start_difficulty.</param>
        /// <param name="type">Initial value of type.</param>
        public static UserSession CreateUserSession(long id, long user_id, long session_id, long correct, long total, double start_difficulty, string type)
        {
            UserSession userSession = new UserSession();
            userSession.id = id;
            userSession.user_id = user_id;
            userSession.session_id = session_id;
            userSession.correct = correct;
            userSession.total = total;
            userSession.start_difficulty = start_difficulty;
            userSession.type = type;
            return userSession;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private long _id;
        partial void OnidChanging(long value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property user_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long user_id
        {
            get
            {
                return this._user_id;
            }
            set
            {
                this.Onuser_idChanging(value);
                this.ReportPropertyChanging("user_id");
                this._user_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("user_id");
                this.Onuser_idChanged();
            }
        }
        private long _user_id;
        partial void Onuser_idChanging(long value);
        partial void Onuser_idChanged();
        /// <summary>
        /// There are no comments for Property session_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long session_id
        {
            get
            {
                return this._session_id;
            }
            set
            {
                this.Onsession_idChanging(value);
                this.ReportPropertyChanging("session_id");
                this._session_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("session_id");
                this.Onsession_idChanged();
            }
        }
        private long _session_id;
        partial void Onsession_idChanging(long value);
        partial void Onsession_idChanged();
        /// <summary>
        /// There are no comments for Property correct in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long correct
        {
            get
            {
                return this._correct;
            }
            set
            {
                this.OncorrectChanging(value);
                this.ReportPropertyChanging("correct");
                this._correct = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("correct");
                this.OncorrectChanged();
            }
        }
        private long _correct;
        partial void OncorrectChanging(long value);
        partial void OncorrectChanged();
        /// <summary>
        /// There are no comments for Property total in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long total
        {
            get
            {
                return this._total;
            }
            set
            {
                this.OntotalChanging(value);
                this.ReportPropertyChanging("total");
                this._total = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("total");
                this.OntotalChanged();
            }
        }
        private long _total;
        partial void OntotalChanging(long value);
        partial void OntotalChanged();
        /// <summary>
        /// There are no comments for Property start_difficulty in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double start_difficulty
        {
            get
            {
                return this._start_difficulty;
            }
            set
            {
                this.Onstart_difficultyChanging(value);
                this.ReportPropertyChanging("start_difficulty");
                this._start_difficulty = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("start_difficulty");
                this.Onstart_difficultyChanged();
            }
        }
        private double _start_difficulty;
        partial void Onstart_difficultyChanging(double value);
        partial void Onstart_difficultyChanged();
        /// <summary>
        /// There are no comments for Property end_difficulty in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<double> end_difficulty
        {
            get
            {
                return this._end_difficulty;
            }
            set
            {
                this.Onend_difficultyChanging(value);
                this.ReportPropertyChanging("end_difficulty");
                this._end_difficulty = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("end_difficulty");
                this.Onend_difficultyChanged();
            }
        }
        private global::System.Nullable<double> _end_difficulty;
        partial void Onend_difficultyChanging(global::System.Nullable<double> value);
        partial void Onend_difficultyChanged();
        /// <summary>
        /// There are no comments for Property color in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string color
        {
            get
            {
                return this._color;
            }
            set
            {
                this.OncolorChanging(value);
                this.ReportPropertyChanging("color");
                this._color = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("color");
                this.OncolorChanged();
            }
        }
        private string _color;
        partial void OncolorChanging(string value);
        partial void OncolorChanged();
        /// <summary>
        /// There are no comments for Property type in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string type
        {
            get
            {
                return this._type;
            }
            set
            {
                this.OntypeChanging(value);
                this.ReportPropertyChanging("type");
                this._type = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("type");
                this.OntypeChanged();
            }
        }
        private string _type;
        partial void OntypeChanging(string value);
        partial void OntypeChanged();
    }
    /// <summary>
    /// There are no comments for MultiLearn.Data.Log.Keystrokes in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MultiLearn.Data.Log", Name="Keystrokes")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Keystrokes : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Keystrokes object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        /// <param name="question_id">Initial value of question_id.</param>
        /// <param name="user_id">Initial value of user_id.</param>
        /// <param name="keycode">Initial value of keycode.</param>
        public static Keystrokes CreateKeystrokes(long id, long question_id, long user_id, long keycode)
        {
            Keystrokes keystrokes = new Keystrokes();
            keystrokes.id = id;
            keystrokes.question_id = question_id;
            keystrokes.user_id = user_id;
            keystrokes.keycode = keycode;
            return keystrokes;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private long _id;
        partial void OnidChanging(long value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property question_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long question_id
        {
            get
            {
                return this._question_id;
            }
            set
            {
                this.Onquestion_idChanging(value);
                this.ReportPropertyChanging("question_id");
                this._question_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("question_id");
                this.Onquestion_idChanged();
            }
        }
        private long _question_id;
        partial void Onquestion_idChanging(long value);
        partial void Onquestion_idChanged();
        /// <summary>
        /// There are no comments for Property user_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long user_id
        {
            get
            {
                return this._user_id;
            }
            set
            {
                this.Onuser_idChanging(value);
                this.ReportPropertyChanging("user_id");
                this._user_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("user_id");
                this.Onuser_idChanged();
            }
        }
        private long _user_id;
        partial void Onuser_idChanging(long value);
        partial void Onuser_idChanged();
        /// <summary>
        /// There are no comments for Property keycode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long keycode
        {
            get
            {
                return this._keycode;
            }
            set
            {
                this.OnkeycodeChanging(value);
                this.ReportPropertyChanging("keycode");
                this._keycode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("keycode");
                this.OnkeycodeChanged();
            }
        }
        private long _keycode;
        partial void OnkeycodeChanging(long value);
        partial void OnkeycodeChanged();
    }
}
